"""Item - Users Relationship

Revision ID: 57b982e30d11
Revises: 67e539c15f52
Create Date: 2025-09-05 16:23:16.410508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57b982e30d11'
down_revision = '67e539c15f52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_item',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['ITEM.idItem'], ),
    sa.ForeignKeyConstraint(['user_id'], ['USERS.idUser'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_item')
    # ### end Alembic commands ###
