"""WG better

Revision ID: 67e539c15f52
Revises: 8edddab039eb
Create Date: 2025-09-03 15:07:20.545589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e539c15f52'
down_revision = '8edddab039eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('WG', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('etage', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('uq_wg_address_etage', ['address', 'etage'])
        batch_op.create_unique_constraint('uq_wg_title', ['title'])
        batch_op.create_foreign_key('fk_wg_creator', 'USERS', ['creator_id'], ['idUser'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('WG', schema=None) as batch_op:
        batch_op.drop_constraint('fk_wg_creator', type_='foreignkey')
        batch_op.drop_constraint('uq_wg_title', type_='unique')
        batch_op.drop_constraint('uq_wg_address_etage', type_='unique')
        batch_op.drop_column('creator_id')
        batch_op.drop_column('description')
        batch_op.drop_column('etage')
        batch_op.drop_column('address')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
