"""public wgs

Revision ID: 803185a6b37d
Revises: 89b36f8537f7
Create Date: 2025-09-15 09:57:34.585613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '803185a6b37d'
down_revision = '89b36f8537f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('WG', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('WG', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
