"""checking shopping lists

Revision ID: 8139d65ebe1b
Revises: 803185a6b37d
Create Date: 2025-09-19 10:09:31.690783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8139d65ebe1b'
down_revision = '803185a6b37d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SHOPPINGLIST', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_checked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SHOPPINGLIST', schema=None) as batch_op:
        batch_op.drop_column('is_checked')

    # ### end Alembic commands ###
