"""Email added to User

Revision ID: 89b36f8537f7
Revises: 57b982e30d11
Create Date: 2025-09-09 13:20:45.746065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b36f8537f7'
down_revision = '57b982e30d11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USERS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strEmail', sa.String(length=128), nullable=False))
        batch_op.create_unique_constraint('uq_user_strEmail', ['strEmail'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USERS', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_strEmail', type_='unique')
        batch_op.drop_column('strEmail')

    # ### end Alembic commands ###
